# This config was inspired by Ham Vocke!
# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# [ Prefix stuff ]
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix
bind R source-file ~/.config/tmux/tmux.conf



# [ Options ]
set -g mouse on                # Enable mouse control (clickable windows, panes, resizable panes)
set -g renumber-windows on
set -g allow-rename off # don't rename windows on command execution

setw -g main-pane-height 65%
setw -g main-pane-width 65%
setw -g window-status-current-style "fg=black,bold"



bind -r [ switch-client -p
bind -r ] switch-client -n
bind ( copy-mode
bind ) copy-mode



# [ Panes ]
# Split panes
unbind '"'
bind -r | split-window -h -c "#{pane_current_path}"
unbind '%'
bind -r - split-window -v -c "#{pane_current_path}"

# Switch to pane
bind -r h if -F "#{window_zoomed_flag}" 'select-pane -L; resize-pane -Z' 'select-pane -L'
bind -r j if -F "#{window_zoomed_flag}" 'select-pane -D; resize-pane -Z' 'select-pane -D'
bind -r k if -F "#{window_zoomed_flag}" 'select-pane -U; resize-pane -Z' 'select-pane -U'
bind -r l if -F "#{window_zoomed_flag}" 'select-pane -R; resize-pane -Z' 'select-pane -R'

# Swap panes
bind -r H select-pane -m \; select-pane -L \; swap-pane -d \; select-pane -M
bind -r J select-pane -m \; select-pane -D \; swap-pane -d \; select-pane -M
bind -r K select-pane -m \; select-pane -U \; swap-pane -d \; select-pane -M
bind -r L select-pane -m \; select-pane -R \; swap-pane -d \; select-pane -M



# [ Windows ]
bind N new-window -c "#{pane_current_path}"
bind r command-prompt -I "#{W}" "rename-window '%%'"
bind -r a last-window
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1
bind -r O rotate-window
unbind &
bind X confirm-before -p "kill-window #{W}? (y/n)" kill-window
