#
# ~/.bashrc
#

[[ $- != *i* ]] && return

colors() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}

[[ -f ~/.extend.bashrc ]] && . ~/.extend.bashrc

[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion



# [BASH PROMPTS]
non_printable() {
    echo -ne "\001$1\002"
}

RESET=$(non_printable "\e[0m")   # End of coloring
COL1=$(non_printable "\e[32m")   # Green
COL2=$(non_printable "\e[34m")   # Blue
COL3=$(non_printable "\e[2;33m") # Dimmed Brown
COL4=$(non_printable "\e[31m")   # Red
export PROMPT_DIRTRIM=2
export PS1="\$(find_status_color)\! $COL1\u $COL2\w $COL3[\$(find_git_branch)] $RESET: "

find_git_branch() {
    git branch --show-current 2> /dev/null
}

find_status_color() {
    if test $? -eq 0
    then
        echo $COL1
    else
        echo $COL4
    fi
}


# [ENV VARIABLES]

# Prevents single command from flooding the history
export HISTCONTROL=ignoredups
export EDITOR="/usr/bin/vim"
# Set environment variables to scale QT applications
export QT_AUTO_SCREEN_FACTOR=1

export PATH="$HOME/Scripts:$PATH"
export PATH="/opt/idea-IU-253.30387.90/bin:$PATH"
export ANDROID_HOME="/home/vilskin/Android/Sdk"
export MANPAGER='vim +Man!'



# [ALIASES]

# Utils
alias ls='ls -F --color=always --group-directories-first'
alias entar='tar -cvzf'
alias untar='tar -xvzf'
alias pacman='pacman --color always'
alias vim='nvim'

alias findkey='xev -event keyboard &'
alias showmimes='cat /usr/share/applications/mimeinfo.cache'

# Common configs
alias editbash="$EDITOR ~/.bashrc"
alias editgit="$EDITOR ~/.gitconfig"
alias edithosts='sudoedit /etc/hosts'
alias editvim="$EDITOR ~/.config/nvim/init.vim"
alias reloadBash='source ~/.bashrc'

# logout and lock require lightdm (or at least dm-tool)
alias lock='light-locker-command -l'
alias off='poweroff'
alias res='reboot'

open () { xdg-open "$1" & };

# Void stuff?
complete -cf sudo
complete -c man

fastfetch
